### ISSUE TITLE
Package fontspec Error: The font "ZapfDingbats" cannot be found.

### ISSUE THREAD

**Issue by JMarianoIFSTTAR** [thruston/Drawing-with-Metapost#2]
Hi

Trying to recompile the document, texlive 2021.20220204-1 / ubuntu 22.04 

Also trying to rebuild on Overleaf (can be considered as a "standard" environment for pdflatex/luatex/xelatex)
https://www.overleaf.com/read/jjnndncwkmbk  (read only)
Same problem

Until now, I didn't find a simple solution to correct this.

Note A) I created a body.tex to contain all the document stuff, apart from the preamble... (easier to maintain)
Note B) I just had to correct previously the same problem with "TeX Gyre Pagella" (requires installing fonts-texgyre, not a big deal)
[and not a problem for Overleaf]

**Comment by thruston** [comment]
Many thanks for the comments -- it's useful to hear from users on other platforms because I work on MacOS, and I do not routinely test for cross platform issues. 

In the short term, I suggest you confine yourself to reading the main document as a PDF and just using the /src/*.mp files as examples for your own work.

You are also welcome to copy my source code and restructure it as you please, so long as you adhere to the original Open Documentation licence.   However if you do this, you are on your own!  

If you feel confident enough to re-organize the source files, and make your own version, then please feel free to find a replacement for Zapf Dingbats.  It's only used for the "manicule" pointer.

```
   \newfontface\ding{Zapf Dingbats}
   \def\hey{\llap{\ding ☞\ }}
```

So I will close this now as "out of scope" but nevertheless I will make a change in a future release so that the document uses a more freely available font, probably Hoefler Text Ornaments.

I will also provide a CONTRIBUTING file in a future release, that will provide more detailed notes for users that want to re-compile the main document, including what fonts they might need to provide.

**Comment by thruston** [comment]
Actually it was much simpler than I thought -- I have removed the dependency on an external Zapf Dingbat font (as you get on mac os) and replaced it with the much older and more widely supported `pifont` package which works just fine on linux, overleaf etc.  See above for the old usage,  it now says:
```
\usepackage{pifont}
\def\hey{\llap{{\ding{43}}\ }}
```
which produces exactly the same output, but should work anywhere.  Thanks for the comment
